# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"hello_nbdev": "00_core.ipynb",
         "helloworld": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://logancyang.github.io/loss_landscapes/"

git_url = "https://github.com/logancyang/loss_landscapes/tree/master/"

def custom_doc_links(name): return None
