# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['hello_nbdev', 'helloworld']

# Cell
def hello_nbdev(d):
    print(d)

def helloworld():
    print('d')